const SCREEN_SCALE_INCREASE = 2;

const MAX_SIZE_WIDTH_SCREEN = 1920
const MAX_SIZE_HEIGHT_SCREEN = 1080
const MIN_SIZE_WIDTH_SCREEN = 270
const MIN_SIZE_HEIGHT_SCREEN = 480
const SIZE_WIDTH_SCREEN = 960*SCREEN_SCALE_INCREASE;
const SIZE_HEIGHT_SCREEN = 540*SCREEN_SCALE_INCREASE;

const MIN_ZOOM = 0.2;
const MAX_ZOOM = 5;

export {
    MAX_SIZE_WIDTH_SCREEN,
    MAX_SIZE_HEIGHT_SCREEN,
    MIN_SIZE_WIDTH_SCREEN,
    MIN_SIZE_HEIGHT_SCREEN,
    SIZE_WIDTH_SCREEN,
    SIZE_HEIGHT_SCREEN,
    MIN_ZOOM,
    MAX_ZOOM,
    SCREEN_SCALE_INCREASE};